### ISSUE TITLE
Aksara bali not found

### ISSUE THREAD

**Issue by teguhteja** [bennylin/transliterasijawa#1]
when i open bali.html from http://bennylin.github.io/transliterasijawa/bali.html there are not found for aksara bali so i try to download it and not found too. Please upload again aksara bali

**Comment by bennylin** [comment]
Saya sudah coba berbagai cara, tidak berhasil memunculkan fon I-Bal-Aksara-Bali.

Saya akhirnya ganti dengan font Noto Sans Balinese. Silakan dicoba kembali.
