### ISSUE TITLE
Menampilkan aksara pasangan

### ISSUE THREAD

**Issue by pakLebah** [bennylin/transliterasijawa#2]
Sebelumnya, saya berterima kasih atas aplikasi translasinya yg sangat bermanfaat. Bagus sekali. 👍

Tapi yg sejak dulu jadi pertanyaan saya, bagaimana cara mengetikkan aksara pasangan? Saya lihat di daftar aksara jawa di unicode, tidak ada aksara pasangan, tapi aplikasi anda bisa menampilkan aksara pasangan, berarti aksara pasangan itu ada di unicode. Lalu cara mengetikkan atau menampilkannya bagaimana? Jika kita bisa menampilkannya secara manual, kan bisa langsung ketik saja tanpa harus translasi lagi.

Terima kasih.

**Comment by pakLebah** [comment]
Lupakan pertanyaan saya di atas, ternyata saya hanya salah pilih font saja. Dengan font yg sesuai, huruf pasangan bisa muncul otomatis setelah *pangkon*. Font Tuladha Jejeg tidak bisa, sebaiknya gunakan font yg lebih modern. Terima kasih.

**Comment by bennylin** [comment]
Saya baru baca ini, mohon maaf m-_-m

Ya, fon akan harus diperbarui ke Noto Sans Javanese 2.0, cuma masih mencari waktu untuk sekaligus memberikan _facelift_ kepada proyek ini.

Sekarang saya lebih fokus mengerjakan keyboard. Silakan dicoba di https://keyman.com/keyboards/jawa, karena multi-platform, termasuk web: https://keymanweb.com/#id-java,Keyboard_jawa

Salam.
