### ISSUE TITLE
sepertinya tidak bekerja?

### ISSUE THREAD

**Issue by 0xh3LL0** [bennylin/transliterasijawa#3]
disitu tertulis 
"Cukup ketikkan kata yang Anda inginkan, dan aksara Jawanya akan langsung muncul."
tapi kok tidak bisa ya?
![vvvv](https://user-images.githubusercontent.com/23132217/78333697-82f6d900-75b4-11ea-84aa-34661e41e388.jpg)

saya coba kolom bawah juga tidak bisa
![vvv2](https://user-images.githubusercontent.com/23132217/78333727-930eb880-75b4-11ea-80e5-01771021d4cc.jpg)

saya pakai firefox 73, win 10

**Comment by 0xh3LL0** [comment]
oops, sepertinya tidak bekerja karena saya pakai adblock

**Comment by bennylin** [comment]
Hmm... ada beberapa laporan yang masuk yang bilang tidak bekerja,

tapi saya tes di tempat saya bekerja, dengan Win 10, FF 71 + Adblock 3.8.4 maupun dengan Chromium

@0xh3LL0, apakah dengan Adblock dimatikan sudah bekerja?
