### ISSUE TITLE
"x" transliteration breaks output

### ISSUE THREAD

**Issue by Porges** [bennylin/transliterasijawa#5]
Entering an "x" always enters a space before the vowel, which breaks the output.

**Comment by Porges** [comment]
Sorry, this is meant to be on the Buginese one.

**Comment by bennylin** [comment]
Fixed. Thank you for the report.
[Diff](https://jv.wikipedia.org/w/index.php?title=Naraguna:Bennylin/trans-bugis.js&diff=prev&oldid=1666522)

**Comment by bennylin** [comment]
![image](https://github.com/bennylin/transliterasijawa/assets/3002108/27729e5d-2a85-4268-a89b-8b2f0a764a3c)

**Comment by Porges** [comment]
> Fixed. Thank you for the report. [Diff](https://jv.wikipedia.org/w/index.php?title=Naraguna:Bennylin/trans-bugis.js&diff=prev&oldid=1666522)

Great, thank you!
